# Home Assistant Operating System release build workflow

name: Release build

on:
  release:
    types: [published]

jobs:
  build:
    name: Release ${{ matrix.board.name }}
    strategy:
      matrix:
        board:
          - {"name": "rpi4_64", "outputs": "rpi4-64"}
          - {"name": "ova", "outputs": "rpi4-64"}
    runs-on: [ "self-hosted", "ubuntu-20.04" ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get version
        id: version
        run: |
          echo "GitHub Event: {{ github.event }}"
          echo "GitHub Event: {{ github.event.release }}"
          echo "GitHub Event: {{ github.event.tag_name }}"
          echo "GitHub Event: {{ github.event.name }}"
      - name: Get version
        id: version
        run: |
          major=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_MAJOR | cut -d'=' -f2)
          build=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_BUILD | cut -d'=' -f2)
          echo "::set-output name=version::$major.$build"

      - name: Build container for Home Assistant OS build
        run: docker build -t haos-builder .

      - name: Build
        run: |
          BUILDER_UID="$(id -u)"
          BUILDER_GID="$(id -g)"
          docker run --rm --privileged -v "${GITHUB_WORKSPACE}:/build" \
            -e BUILDER_UID="${BUILDER_UID}" -e BUILDER_GID="${BUILDER_GID}" \
            -v "haos-build-cache:/cache" \
            haos-builder make ${{ matrix.board.name }}

      - name: Get version
        id: version
        run: |
          major=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_MAJOR | cut -d'=' -f2)
          build=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_BUILD | cut -d'=' -f2)
          echo "::set-output name=version::$major.$build"

      - name: Upload disk image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.img.gz
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.img.gz
          asset_content_type: application/gzip

      - name: Upload rauc update
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.raucb
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.raucb
          asset_content_type: application/octet-stream

      - name: Upload qcow2 image
        if: ${{ matrix.board.name == 'ova' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.qcow2.gz
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.qcow2.gz
          asset_content_type: application/gzip

      - name: Upload vdi image
        if: ${{ matrix.board.name == 'ova' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vdi.gz
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vdi.gz
          asset_content_type: application/gzip

      - name: Upload vhdx image
        if: ${{ matrix.board.name == 'ova' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vhdx.gz
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vhdx.gz
          asset_content_type: application/gzip

      - name: Upload vmdk image
        if: ${{ matrix.board.name == 'ova' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${GITHUB_WORKSPACE}/release/hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vmdk.gz
          asset_name: hassos_${{ matrix.board.output }}-${{ steps.version.outputs.version }}.vmdk.gz
          asset_content_type: application/gzip
