# Home Assistant Operating System build workflow

name: Test action

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: [ "ubuntu-22.04" ]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v2
      - name: Execute stuff
        shell: bash
        run: |
          set -x
          df -h
          pwd
          ls -lah
          df -h .
          echo "And the mounts are"
          cat /proc/mounts
          echo "Content of /mnt"
          ls -la /mnt
          cat /mnt/DATALOSS_WARNING_README.txt
          echo "Test /mnt"
          sudo dd if=/dev/zero of=/mnt/testfile bs=1G count=1 oflag=direct
          echo "Test /"
          sudo dd if=/dev/zero of=/testfile bs=1G count=1 oflag=direct
          sudo rm -rf /usr/share/dotnet
          df -h
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          df -h

